// Datapack Generator - 数据包生成器
import type { McFunction, Namespace } from '../../types'

export interface GeneratorOptions {
  formatVersion: number
  description: string
}

const DEFAULT_OPTIONS: GeneratorOptions = {
  formatVersion: 48,
  description: 'Generated by MC Command Editor',
}

export class DatapackGenerator {
  private options: GeneratorOptions

  constructor(options?: Partial<GeneratorOptions>) {
    this.options = { ...DEFAULT_OPTIONS, ...options }
  }

  generatePackMeta(): string {
    return JSON.stringify({
      pack: {
        pack_format: this.options.formatVersion,
        description: this.options.description,
      },
    }, null, 2)
  }

  generateFunction(func: McFunction): string {
    return func.commands
      .map((cmd) => {
        const raw = cmd.raw || ''
        return raw.startsWith('/') ? raw.slice(1) : raw
      })
      .join('\n')
  }

  generateNamespace(ns: Namespace): Map<string, string> {
    const files = new Map<string, string>()

    for (const func of ns.functions) {
    const path = `data/${ns.name}/function/${func.name}.mcfunction`
    files.set(path, this.generateFunction(func))
  }

    return files
  }
}
